In [51]:
import numpy as np

In [52]:
# Задание 1

In [53]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [54]:
# Задание 2

In [55]:
a1 = a.reshape(3, 4)
a1

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [56]:
a2 = a.reshape(4, 3)
a2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [57]:
a3 = a.reshape(2, 6)
a3

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [58]:
a4 = a.reshape(6, 2)
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [59]:
a5 = a.reshape(12, 1)
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [60]:
# Задание 3

In [61]:
a6 = a.reshape(2, -1)
a6

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [62]:
a7 = a.reshape(3, -1)
a7

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [63]:
a8 = a.reshape(4, -1)
a8

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [64]:
a9 = a.reshape(-1, 2)
a9

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [65]:
a10 = a.reshape(-1, 3)
a10

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [66]:
# Задание 4

In [67]:
# Нет, нельзя.

In [68]:
# Задание 5

In [69]:
c = np.random.randn(3, 4)
c

array([[-1.72491783, -0.56228753, -1.01283112,  0.31424733],
       [-0.90802408, -1.4123037 ,  1.46564877, -0.2257763 ],
       [ 0.0675282 , -1.42474819, -0.54438272,  0.11092259]])

In [70]:
c.size

12

In [71]:
d = c.reshape(1, 12)
d

array([[-1.72491783, -0.56228753, -1.01283112,  0.31424733, -0.90802408,
        -1.4123037 ,  1.46564877, -0.2257763 ,  0.0675282 , -1.42474819,
        -0.54438272,  0.11092259]])

In [72]:
d.size

12

In [73]:
# Задание 6

In [74]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [75]:
# Задание 7

In [76]:
b = np.arange(20, 1, -2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [77]:
# Между массивами a и b нет никакой разницы.

In [78]:
# Задание 8

In [79]:
a = np.zeros((2, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [80]:
b = np.ones((3, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [81]:
c = np.vstack((a, b))
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [82]:
# Задание 9

In [83]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [84]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [85]:
A_t = A.T
A_t

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [86]:
B = A.dot(A_t)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [87]:
B.size

16

In [88]:
d = np.linalg.det(B)
d

0.0

In [89]:
# Обратную матрицу для матрицы B вычислить не получится, поскольку её определитель равен 0.

In [90]:
# Задание 10

In [91]:
np.random.seed(42)
np.random.rand(10)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [92]:
np.random.seed(42)
np.random.rand(10)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [93]:
# Задание 11

In [94]:
c = np.random.randint(0, 16, (1, 16))
c

array([[ 5,  4,  1,  7, 11, 13,  5,  1, 15, 11,  4,  0, 11,  9,  5, 12]])

In [95]:
# Задание 12

In [96]:
C = c.reshape(4, 4)
C

array([[ 5,  4,  1,  7],
       [11, 13,  5,  1],
       [15, 11,  4,  0],
       [11,  9,  5, 12]])

In [97]:
D = (C * 10) + B
D

array([[ 55,  54,  33, 102],
       [124, 180, 136, 132],
       [173, 196, 189, 212],
       [142, 212, 262, 422]])

In [98]:
d = np.linalg.det(D)
d

72557599.99999987

In [99]:
r = np.linalg.matrix_rank(D)
r

4

In [100]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00980683, -0.01670645,  0.02091966, -0.00765406],
       [ 0.00539875,  0.02483241, -0.02053706,  0.0012448 ],
       [-0.02579633, -0.00913233,  0.01239567,  0.00286448],
       [ 0.01000364, -0.00118361, -0.00441801,  0.00254143]])