In [49]:
# 2*. Найти 𝐿-матрицу 𝐿𝑈-разложения для матрицы коэффициентов.

In [50]:
import numpy as np

In [51]:
# а)

In [52]:
a = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])

In [53]:
def LU_decomposition(a):
    L = np.eye(len(a))
    U = np.zeros(np.shape(a))
    for r in range(1, len(a)):
        U[0, r - 1] = a[0, r - 1]
        L[r, 0] = a[r, 0] / a[0, 0]
    U[0, -1] = a[0, -1]
    for r in range(1, len(a)):
        for i in range(r, len(a)):
            delta = 0
            for k in range(0, r):
                delta += L[r, k] * U[k, i]
            U[r, i] = a[r, i] - delta
            for i in range(r + 1, len(a)):
                theta = 0
                for k in range(0, r):
                    theta += L[i, k] * U[k, r]
                L[i, r] = (a[i, r] - theta) / U[r, r]
    return L

In [54]:
print('L-матрица LU-разложения:')
print(LU_decomposition(a))

L-матрица LU-разложения:
[[1. 0. 0.]
 [2. 1. 0.]
 [3. 4. 1.]]


In [55]:
# Проверка работы функции посредством библиотеки SymPy:

In [56]:
from sympy import *

In [57]:
a = Matrix([[1, 2, 4], [2, 9, 12], [3, 26, 30]])

In [58]:
L, U, _ = a.LUdecomposition()
print('L-матрица LU-разложения:')
L

L-матрица LU-разложения:


Matrix([
[1, 0, 0],
[2, 1, 0],
[3, 4, 1]])

In [59]:
# б)

In [60]:
a = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])

In [61]:
print('L-матрица LU-разложения:')
print(LU_decomposition(a))

L-матрица LU-разложения:
[[1. 0. 0. 0.]
 [2. 1. 0. 0.]
 [3. 5. 1. 0.]
 [4. 6. 7. 1.]]


In [62]:
# Проверка работы функции посредством библиотеки SymPy:

In [63]:
a = Matrix([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])

In [64]:
L, U, _ = a.LUdecomposition()
print('L-матрица LU-разложения:')
L

L-матрица LU-разложения:


Matrix([
[1, 0, 0, 0],
[2, 1, 0, 0],
[3, 5, 1, 0],
[4, 6, 7, 1]])