In [55]:
# 1. Найти с помощью NumPy SVD для матрицы.

In [56]:
from numpy import array
from numpy.linalg import norm
from scipy.linalg import svd

In [57]:
a = array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])

In [58]:
print(f'Матрица A:\n{a}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [59]:
U, D, VT = svd(a)

In [60]:
print(f'Матрица U:\n{U}')

Матрица U:
[[ 0.17056501  0.15680918 -0.53077508 -0.79905375 -0.16158397]
 [ 0.39287016 -0.52933945  0.6134793  -0.43375771  0.03082495]
 [-0.14366152 -0.82449256 -0.52379105  0.14049848  0.07400343]
 [ 0.88843702  0.06074346 -0.24655277  0.37755832 -0.06042632]
 [ 0.08125046  0.10831843 -0.08231425 -0.10524851  0.98173958]]


In [61]:
print(f'Матрица D:\n{D}')

Матрица D:
[8.82486885 6.14060608 2.53271528]


In [62]:
print(f'Матрица V^T:\n{VT}')

Матрица V^T:
[[ 0.07116451  0.71702467  0.69340553]
 [-0.36737824  0.66514082 -0.65009301]
 [-0.92734505 -0.20847855  0.31075368]]


In [63]:
# 2. Для матрицы из предыдущего задания найти:
# а) евклидову норму;
# б) норму Фробениуса.

In [64]:
a_euclidean_norm = norm(D)
print(f'Евклидова норма матрицы A:\n{a_euclidean_norm}')

# Ответ: 11.045361017187261

Евклидова норма матрицы A:
11.045361017187261


In [65]:
a_frobenius_norm = norm(a, 'fro')

In [66]:
print(f'Норма Фробениуса матрицы A:\n{a_frobenius_norm}')

# Ответ: 11.045361017187261

Норма Фробениуса матрицы A:
11.045361017187261
