In [500]:
# 1. Найти скалярное произведение векторов  𝑥,𝑦 ∈ ℝ :

In [501]:
import numpy as np

In [502]:
# а) 𝑥=(0,−3,6), 𝑦=(−4,7,9); 

In [503]:
x = np.array([0, -3, 6])
y = np.array([-4, 7, 9])
xy_dot_product = np.dot(x, y)
print(f'Скалярное произведение векторов x и y = {xy_dot_product}')

Скалярное произведение векторов x и y = 33


In [504]:
# б) 𝑥=(7,−4,0,1), 𝑦=(−3,1,11,2).

In [505]:
x = np.array([7, -4, 0, 1])
y = np.array([-3, 1, 11, 2])
xy_dot_product = np.dot(x, y)
print(f'Скалярное произведение векторов x и y = {xy_dot_product}')

Скалярное произведение векторов x и y = -23


In [506]:
# 2. Найти нормы векторов (4,2,4) и (12,3,4) и угол между ними.

In [507]:
import math
from numpy.linalg import norm

a = np.array([4, 2, 4])
b = np.array([12, 3, 4])

In [508]:
a_norm = np.linalg.norm(a)
print(f'Норма вектора a = {a_norm}')

Норма вектора a = 6.0


In [509]:
b_norm = np.linalg.norm(b)
print(f'Норма вектора b = {b_norm}')

Норма вектора b = 13.0


In [510]:
unit_a = a / a_norm
unit_b = b / b_norm
ab_dot_product = np.dot(unit_a, unit_b)

In [511]:
ab_angle = int(math.degrees(np.arccos(ab_dot_product)))
print(f'Угол между векторами a и b = {ab_angle} градусов')

Угол между векторами a и b = 26 градусов


In [512]:
# 4. Какие из нижеперечисленных векторов образуют ортонормированный базис в линейном пространстве ℝ3:
# а) (1,0,0),(0,0,1); 
# б) (1/√2,−1/√2,0),(1/√2,1/√2,0),(0,0,1); 
# в) (1/2,−1/2,0),(0,1/2,1/2),(0,0,1); 
# г) (1,0,0),(0,1,0),(0,0,1)?

In [513]:
# а) (1,0,0),(0,0,1)

In [514]:
a = np.array([1, 0, 0])
b = np.array([0, 0, 1])
ab_dot_product = np.dot(a, b)
print(ab_dot_product)

0


In [ ]:
# а) Образуют.

In [515]:
# б) (1/√2,−1/√2,0),(1/√2,1/√2,0),(0,0,1)

In [516]:
a = np.array([1/(2**1/2), -1/(2**1/2), 0])
b = np.array([1/(2**1/2), 1/(2**1/2), 0])
c = np.array([0, 0, 1])
abc_dot_product = np.dot(np.dot(a, b), c)
print(abc_dot_product)

[0. 0. 0.]


In [ ]:
# б) Образуют.

In [517]:
# в) (1/2,−1/2,0),(0,1/2,1/2),(0,0,1)

In [518]:
a = np.array([1/2, -1/2, 0])
b = np.array([0, 1/2, 1/2])
c = np.array([0, 0, 1])
abc_dot_product = np.dot(np.dot(a, b), c)
print(abc_dot_product)

[ 0.    0.   -0.25]


In [ ]:
# в) Не образуют.

In [519]:
# г) (1,0,0),(0,1,0),(0,0,1)

In [520]:
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])
c = np.array([0, 0, 1])
abc_dot_product = np.dot(np.dot(a, b), c)
print(abc_dot_product)

[0 0 0]


In [ ]:
# г) Образуют.